//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyPetsRescue.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyPetsRescueEntities : DbContext
    {
        public HappyPetsRescueEntities()
            : base("name=HappyPetsRescueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdoptedPet> AdoptedPet { get; set; }
        public virtual DbSet<AdoptionStatus> AdoptionStatus { get; set; }
        public virtual DbSet<Breed> Breed { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<PetType> PetType { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
